apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: myapp
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: worawut2547/cloud-project:backend-1
        ports:
        - containerPort: 3003