apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: myapp
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z database-svc 5432; do echo waiting for database; sleep 2; done;']
      containers:
      - name: backend-container
        image: worawut2547/cloud-project:daily-hub-be-{{ image_tag}}
        ports:
        - containerPort: 3003