apiVersion: v1
kind: Service
metadata:
  name: daily-hub-backend-svc
  namespace: myapp
spec:
  type: NodePort
  selector:
    app: daily-hub-backend
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
      nodePort: 30003 # เข้าไดจาก vm_ip:30003