apiVersion: v1
kind: Service
metadata:
  name: database-svc
  namespace: myapp
spec:
  type: NodePort
  selector:
    app: database
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30542 # เข้าไดจาก vm_ip:35432
