---
- name: Install Kubernetes tools and Setup Kind Cluster
  hosts: vm_app_node
  tasks:
    # 1. ติดตั้ง kubectl
    - name: Download kubectl binary
      become: yes
      get_url:
        url: "https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: "0755"

    # 2. ติดตั้ง Kind
    - name: Download Kind binary
      become: yes
      get_url:
        url: "https://kind.sigs.k8s.io/dl/v0.23.0/kind-linux-amd64"
        dest: /usr/local/bin/kind
        mode: "0755"

    # --- เพิ่มเติม: สร้างโฟลเดอร์ .kube รอไว้ ---
    - name: Ensure .kube directory exists
      file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        mode: "0755"

    # 3. สร้าง Cluster
    - name: Check if Kind cluster exists
      command: kind get clusters
      register: kind_clusters
      changed_when: false

    - name: Create Kind Cluster if not exists
      command: >
        kind create cluster
        --name my-cluster
        --kubeconfig /home/{{ ansible_user }}/.kube/config
      when: "'my-cluster' not in kind_clusters.stdout"

    - name: Ensure correct ownership of kubeconfig
      become: yes
      file:
        path: "/home/{{ ansible_user }}/.kube/config"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"

    # 4. ตรวจสอบสถานะ (เพิ่มหน่วงเวลารอ API Server)
    - name: Wait for cluster to be ready
      command: kubectl cluster-info
      register: k8s_info
      changed_when: false
      retries: 5 # <--- ลองเช็คซ้ำ 5 รอบ
      delay: 10 # <--- เว้นระยะรอบละ 10 วินาที
      until: k8s_info is succeeded

    - name: Print Cluster Info
      debug:
        msg: "{{ k8s_info.stdout }}"
