apiVersion: v1
kind: Service
metadata:
  name: daily-hub-frontend-svc
  namespace: myapp
spec:
  selector:
    app: daily-hub-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP