---
- name: Deploy Application to Kubernetes
  hosts: all
  tasks:
    - name: Copy k8s manifests to remote
      copy:
        src: "../../k8s/"
        dest: /home/{{ ansible_user }}/k8s/
        mode: "0644"
    
    - name: Apply Namespace
      command: kubectl apply -f /home/{{ ansible_user }}/k8s/namespace.yaml

    - name: Update Backend Image Tags in Manifests
      replace:
        path: "/home/{{ ansible_user }}/k8s/backend/deploy.yaml"
        regexp: 'image: worawut2547/cloud-project:daily-hub-be-.*'
        replace: 'image: worawut2547/cloud-project:daily-hub-be-{{ image_tag }}'
    
    - name: Update Frontend Image Tags in Manifests
      replace:
        path: "/home/{{ ansible_user }}/k8s/frontend/deploy.yaml"
        regexp: 'image: worawut2547/cloud-project:daily-hub-fe-.*'
        replace: 'image: worawut2547/cloud-project:daily-hub-fe-{{ image_tag }}'

    - name: Apply Database
      command: kubectl apply -R -f /home/{{ ansible_user }}/k8s/database/

    - name: Apply Backend
      command: kubectl apply -R -f /home/{{ ansible_user }}/k8s/backend/

    - name: Apply Frontend
      command: kubectl apply -R -f /home/{{ ansible_user }}/k8s/frontend/
    
    - name: Wait for Deployments to be ready
      command: kubectl rollout status deployment/{{ item }} -n myapp
      loop:
        - backend-deployment
        - frontend-deployment
        - database-deployment
      retries: 5
      delay: 10